import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Providers from "./providers";

const roboto = Roboto({
	weight: ["300", "400", "500", "700"],
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "TailStore",
	description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
		<html lang="en" className={`${roboto.className} h-full antialiased`}>
			<body className="min-h-full flex flex-col">
				<Providers>
					<Header />
					{children}
					<Footer />
				</Providers>
			</body>
		</html>
  );
}
